### ISSUE TITLE
Respecting asymmetries in injections

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/aframev2#156]
Re-filing the [issue](https://github.com/ML4GW/aframe/issues/402) from the old repo. We should sample waveform kernels such that the coalescence point is allowed to be all the way at the right edge, but not at the left edge.

**Comment by EthanMarx** [comment]
Instead of saving the waveforms centered, I think we add some `right_padding` argument that specifies how far from the right edge of the timeseries the coalescence lies. This will be saved with the signal dataset. 

Then, the `trigger_offset` specifies how far from the _left_ edge of the kernel  the coalescence is forced to lie. We will force no constraint on the right edge.

When sampling kernels we'll need to pad the right edge with `kernel_length` - `right_padding` - `trigger_offset` worth of zeros. Then, we can sample `start_idx` such that the `start_idx` isn't too close to the coalescence time

**Comment by wbenoit26** [comment]
Yeah, I generally agree with that outline. We should include the ability to specify a distance from right edge for the case of signals where the defining signal time isn't at the end (thinking ahead a bit to the ringdown search).

I'm not sure there's a ton of benefit in not centering the signals, but I also have reason to not _not_ center the signals, so I'm down to try out that parameterization. Regardless, the coalescence point of the signals is something that we ought to be saving as an attribute of the signal file.

**Comment by wbenoit26** [comment]
Closed by #158
