### ISSUE TITLE
Unable to access dict Attributes in train/data/base.py and train/model/base.py

### ISSUE THREAD

**Issue by sjhend03** [ML4GW/aframev2#205]
In `aframev2/projects/train/train/data/base.py` and `aframev2/train/train/model/base.py` instances of `self.hparams.{attribute}` caused AttributeErrors with errors similar to,
```
AttributeError: 'AttributeDict' object has no attribute 'data_dir' 
```

It started to work by changing all instances of `self.hparams.{attribute}` to `self.hparams.init_args["{attribute}"]`

**Comment by EthanMarx** [comment]
Hey @sjhend03 encountered this too. Turns out it was a bug with pytorch lightning. (see [here](https://github.com/Lightning-AI/pytorch-lightning/issues/19977#issuecomment-2198328473)). 

This should already be fixed in the train project by constraining lightning to <2.3.0. 

So, try re-building your train container and try again.

**Comment by EthanMarx** [comment]
@sjhend03 going to close this but feel free to reopen if issue persists for whatever reason
